version: 0.0
os: linux
files:
  - source: target/aws-cicd-demo-1.0.0.jar
    destination: /home/ec2-user/app/
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ec2-user
