version: 0.0
os: linux
files:
  - source: target/aws-cicd-demo-1.0.0.jar
    destination: /home/ubuntu/app/
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
