version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven
      - mvn --version
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
artifacts:
  files:
    - target/*.jar
